
services:
  pg-admin-dev:
    image: dpage/pgadmin4:8.9
    networks:
      - dev_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5051:5050"
      
volumes:
  dev_data:

networks:
  dev_network:
 