
services:
  pg-admin:
    image: dpage/pgadmin4:8.9
    networks:
      - prod_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
      
volumes:
  prod_data:

networks:
  prod_network:
 